version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123
    networks:
      - app-network
  back:
    image: "node:lts"
    container_name: back
    user: "node"
    working_dir: /home/node/app
    depends_on:
      - "mongo"
    environment:
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=123
      - MONGO_HOSTNAME=db
      - MONGO_PORT=27017
    volumes:
      - ./Back:/home/node/app
    expose:
      - "51808"
    ports:
      - 51808:51808
    networks:
      - app-network
    command: "npm start"
  front:
    image: "node:lts"
    container_name: front
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./Front:/home/node/app
    expose:
      - "8080"
    ports:
      - 8080:8080
    networks:
      - app-network
    command: bash -c "npm run dev"
networks:
  app-network:
    driver: bridge